apiVersion: v1
kind: Secret
metadata:
  name: openai-api-secret
type: Opaque
data:
  OPENAI_API_KEY: "Rnd0WUJJcnpxakVmdWs1dWwxS2VTdEFPM0drWGdtR3RmUDJKMlVVNnJlMEF5OERDRGhHeUpRUUo5OUFMQUNmaE1rNVhKM3czQUFBQkFDT0dKSVFO"
# Note: The value of OPENAI_API_KEY must be Base64-encoded.
# You can encode it using the following command:
# echo -n "your-actual-api-key" | base64

